# 데이터 전처리
## 레이블 인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [4]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [10]:
def get_name(model, num):
    return model.inverse_transform([num])[0]

get_name(encoder, 3)

'선풍기'

##  One-Hot Encoding(or Vector)

In [13]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder  = LabelEncoder()     #숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder.fit(items)
labels = encoder.transform(items)

labels=labels.reshape(-1,1)     #2차원 데이터로 변환

oh_encoder = OneHotEncoder()   #One-Hot encoding 적용
oh_encoder.fit(labels)

oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [16]:
import pandas as pd

df = pd.DataFrame({'items': ['TV', '냉장고', '전자레인지', 
                             '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

## Feature 스케일링

### StandardScaler

In [18]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()  #붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns= iris.feature_names)

print('feature 들의 평균')
print(iris_df.mean())

print('\n feature 들의 분산')
print(iris_df.var())

feature 들의 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

 feature 들의 분산
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


C:\Users\pc\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()  #StandardScaler 객체 생성
scaler.fit(iris_df)       #StandardScaler로 데이터셋 변환. fit() 과 transform() 호출
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)

print('feature 들의 평균')
print(iris_df_scaled.mean())

print('\n feature 들의 분산')
print(iris_df_scaled.var())

feature 들의 평균
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

 feature 들의 분산
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()  #MinMaxScaler 객체 생성
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 MIN')
print(iris_df_scaled.min())

print('\n feature 들의 MAX')
print(iris_df_scaled.max())

feature 들의 MIN
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

 feature 들의 MAX
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
